#Minecraft server properties
server-port=25565
level-name=Survival
level-seed=
level-type=DEFAULT
gamemode=survival
difficulty=normal
max-players=20
online-mode=true
pvp=true
spawn-protection=16
view-distance=10
motd=§6Willkommen auf dem Server! §a10 Welten zum Erkunden!
enable-command-block=true
allow-flight=false
white-list=false
